### ISSUE TITLE
Avatar marker has disappeared

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1285] opened 2020-02-25 15:09 UTC
**Describe the bug**
There used to be a blue marker on top of the player's avatar so they could differentiate theirs from the others.
The marker has now mysteriously vanished.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any Kurono game.
2. Observe that your avatar doesn't have a marker on top of it.
**Optional extra steps:***
3. Add 10 test avatars to your game.
4. Observe the full extent of the bug as you painstakingly try to locate your avatar.

**Expected behavior**
The player's avatar should have a blue marker on top of it.

**Screenshots**
What it used to look like:
![Selection_001.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/46b27415-1f25-4979-a198-6a1a547fe4ce)

What it looks like now:
![Workspace 1_005.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/d0ec19fc-ee1c-4333-81e1-269f0049e8ee)

**Comment by mrniket** [comment] 2020-02-26 16:27
I can't reproduce this locally on development nor on staging, perhaps it was fixed by #1276?

**Comment by mrniket** [comment] 2020-02-27 13:38
Can't reproduce this on staging, production or locally. Closing

**Closed by mrniket** 2020-02-27 13:38 UTC
Labels: Development, bug
